--1
set echo on
DROP TABLE ZAMOWIENIA CASCADE CONSTRAINTS;
DROP TABLE WAREHOUSE CASCADE CONSTRAINTS;
DROP TABLE TITLE CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE PRODUKT CASCADE CONSTRAINTS;
DROP TABLE POZYCJA CASCADE CONSTRAINTS;
DROP TABLE ORD CASCADE CONSTRAINTS;
DROP TABLE LONGTEXT CASCADE CONSTRAINTS;
DROP TABLE KLIENT CASCADE CONSTRAINTS;
DROP TABLE INVENTORY CASCADE CONSTRAINTS;
DROP TABLE IMAGE CASCADE CONSTRAINTS;
DROP TABLE EMP CASCADE CONSTRAINTS;
DROP TABLE DEPT CASCADE CONSTRAINTS;
DROP TABLE APEX$_ACL CASCADE CONSTRAINTS;
DROP TABLE APEX$_WS_FILES CASCADE CONSTRAINTS;
DROP TABLE APEX$_WS_HISTORY CASCADE CONSTRAINTS;
DROP TABLE APEX$_WS_LINKS CASCADE CONSTRAINTS;
DROP TABLE APEX$_WS_NOTES CASCADE CONSTRAINTS;
DROP TABLE APEX$_WS_ROWS CASCADE CONSTRAINTS;
DROP TABLE APEX$_WS_TAGS CASCADE CONSTRAINTS;
DROP TABLE APEX$_WS_WEBPG_SECTION_HISTORY CASCADE CONSTRAINTS;
DROP TABLE APEX$_WS_WEBPG_SECTIONS CASCADE CONSTRAINTS;
DROP TABLE DEMO_USERS CASCADE CONSTRAINTS;
DROP TABLE DEMO_CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE DEMO_ORDERS CASCADE CONSTRAINTS;
DROP TABLE DEMO_PRODUCT_INFO CASCADE CONSTRAINTS;
DROP TABLE DEMO_ORDER_ITEMS CASCADE CONSTRAINTS;
DROP TABLE DEMO_STATES CASCADE CONSTRAINTS;
set echo off

--2
-- Generated by Oracle SQL Developer Data Modeler 20.04.0.374.0801
-- at:          2021-05-19 21:02:44 CEST
-- site:        Oracle Database 11g
-- type:        Oracle Database 11g

--predefined type, no DDL - MDSYS.SDO_GEOMETRY

--predefined type, no DDL - XMLTYPE
CREATE TABLE cars (
    car_id     VARCHAR(20) NOT NULL,
    car_brand  VARCHAR(50) NOT NULL,
    car_model  VARCHAR(30) NOT NULL,
    vintage    DATE NOT NULL,
    value      NUMBER(7)
)
LOGGING;

ALTER TABLE cars ADD CONSTRAINT cars_pk PRIMARY KEY ( car_id );

CREATE TABLE customer (
    customer_id     NUMBER(7) NOT NULL,
    last_name       VARCHAR(25) NOT NULL,
    first_name      VARCHAR(25),
    street_address  VARCHAR(40),
    city            VARCHAR(25),
    state           VARCHAR(2),
    zip             VARCHAR(20),
    cars_car_id     VARCHAR(20) NOT NULL,
    loans_loan_id   NUMBER(7) NOT NULL
)

logging;

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customer_id );

CREATE TABLE loans (
    loan_id         NUMBER(7) NOT NULL,
    loan_date       DATE NOT NULL,
    payment_method  VARCHAR(10) NOT NULL,
    loan_expense    NUMBER(7)
)

logging;

ALTER TABLE loans ADD CONSTRAINT loans_pk PRIMARY KEY ( loan_id );

ALTER TABLE customer
    ADD CONSTRAINT customer_cars_fk FOREIGN KEY ( cars_car_id )
        REFERENCES cars ( car_id )
    NOT DEFERRABLE;

ALTER TABLE customer
    ADD CONSTRAINT customer_loans_fk FOREIGN KEY ( loans_loan_id )
        REFERENCES loans ( loan_id )
    NOT DEFERRABLE;	



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE				3
-- CREATE INDEX				0
-- ALTER TABLE				5
-- CREATE VIEW				0
-- ALTER VIEW				0
-- CREATE PACKAGE			0
-- CREATE PACKAGE BODY			0
-- CREATE PROCEDURE			0
-- CREATE FUNCTION			0
-- CREATE TRIGGER			0
-- ALTER TRIGGER			0
-- CREATE COLLECTION TYPE		0
-- CREATE STRUCTURED TYPE		0
-- CREATE STRUCTURED TYPE BODY		0
-- CREATE CLUSTER			0
-- CREATE CONTEXT			0
-- CREATE DATABASE			0
-- CREATE DIMENSION			0
-- CREATE DIRECTORY			0
-- CREATE DISK GROUP			0
-- CREATE ROLE				0
-- CREATE ROLLBACK SEGMENT		0
-- CREATE SEQUENCE 			0
-- CREATE MATERIALIZED VIEW		0
-- CREATE MATERIALIZED VIEW LOG		0
-- CREATE SYNONYM			0
-- CREATE TABLESPACE			0
-- CREATE USER				0
--
-- DROP TABLESPACE			0
-- DROP DATABASE			0
--
-- REDACTION POLICY			0
--
-- ORDS DROP SCHEMA			0
-- ORDS ENABLE SCHEMA			0
-- ORDS ENABLE OBJECT			0
--
-- ERRORS				0
-- WARNINGS				0

--3
SELECT table_name FROM user_tables;

--4
DESCRIBE cars;
DESCRIBE customer;
DESCRIBE loans;

--5
SELECT  constraint_name, constraint_type, search_condition FROM user_constraints
WHERE TABLE_NAME = 'CARS';
SELECT constraint_name, constraint_type, search_condition FROM user_constraints
WHERE TABLE_NAME = 'CUSTOMER';
SELECT constraint_name, constraint_type, search_condition FROM user_constraints
WHERE TABLE_NAME = 'LOANS';

--6
--ALTER TABLE
CREATE TABLE telefony_klienci (
    numer_telefonu  varchar(20) NOT NULL,
    id_klienta      INTEGER NOT NULL,
    PRIMARY KEY ( numer_telefonu )
);
ALTER TABLE telefony_klienci
    ADD CONSTRAINT klient_id FOREIGN KEY ( id_klienta )
        REFERENCES customer ( customer_id );
 
-- TABLICOWA
CREATE TABLE telefony_klienci (
    numer_telefonu  VARCHAR(20) NOT NULL,
    id_klienta      INTEGER NOT NULL,
    PRIMARY KEY ( numer_telefonu ),
    CONSTRAINT klient_id FOREIGN KEY ( id_klienta )
        REFERENCES customer ( customer_id )
);


--KOLUMNOWA 
CREATE TABLE telefony_klienci (
    numer_telefonu  VARCHAR(20) NOT NULL,
    id_klienta      INTEGER NOT NULL,
    CONSTRAINT    klient_id
        REFERENCES customer ( customer_id ),
    PRIMARY KEY ( numer_telefonu )
);


--7
ALTER TABLE customer
ADD CONSTRAINT unique_last_name
UNIQUE(last_name);

--8
INSERT INTO cars VALUES(1,'Skoda', 'Octavia', '2015-01-01',45000);
INSERT INTO cars VALUES( 2,'Fiat', 'Punto','2003-01-01', 5000 );
INSERT INTO cars VALUES(3,'Audi', 'A6','2009-01-01', 145000);
INSERT INTO cars VALUES(4,'Ford', 'Mondeo','2009-01-01', 24000);

INSERT INTO loans VALUES(1, '2021-03-29' , 'cash',2700);
INSERT INTO loans VALUES(2, '2020-12-29','card',10000);
INSERT INTO loans VALUES(3, '2021-01-10','cash',400);

INSERT INTO customer VALUES(1,'Zygadlo','Albert','Gleboka', 'Lublin', 'PL', '20-610',2,1);
INSERT INTO customer VALUES(2,'Adamski','Stefan','Lipowa', 'Lublin', 'PL', '20-560',1,3);
INSERT INTO customer VALUES(3,'Smialek','Zofia','Leszczynskiego', 'Lublin', 'PL', '20-900',3,2);

INSERT INTO telefony_klienci VALUES('721889331',1);
INSERT INTO telefony_klienci VALUES('721889211',2);
INSERT INTO telefony_klienci VALUES('721219331',3);

--9
SELECT * FROM CUSTOMER;

--10
UPDATE customer
SET first_name = 'Anna'
WHERE customer.first_name = 'Stefan';

--11
SELECT * FROM CUSTOMER;

--12
CREATE TABLE emp 
(id                         NUMBER(7) 
   CONSTRAINT emp_id_nn NOT NULL,
 last_name                  VARCHAR2(25) 
   CONSTRAINT emp_last_name_nn NOT NULL,
 first_name                 VARCHAR2(25),
 userid                     VARCHAR2(8),
 start_date                 DATE,
 comments                   VARCHAR2(255),
 manager_id                 NUMBER(7),
 title                      VARCHAR2(25),
 dept_id                    NUMBER(7),
 salary                     NUMBER(11, 2),
 commission_pct             NUMBER(4, 2),
     CONSTRAINT emp_id_pk PRIMARY KEY (id),
     CONSTRAINT emp_userid_uk UNIQUE (userid),
     CONSTRAINT emp_commission_pct_ck
        CHECK (commission_pct IN (10, 12.5, 15, 17.5, 20)));
INSERT INTO emp VALUES (
  1, 'Velasquez', 'Carmen', 'cvelasqu',
   to_date('03-MAR-1990 8:30', 'dd-mon-yyyy hh24:mi'), NULL, NULL, 'President',
   50, 2500, NULL);
INSERT INTO emp VALUES (
   2, 'Ngao', 'LaDoris', 'lngao',
   to_date('08-MAR-1990', 'dd-mon-yyyy'), NULL, NULL, 'VP, Operations',
   41, 1450, NULL);
INSERT INTO emp VALUES (
   3, 'Nagayama', 'Midori', 'mnagayam',
   to_date('17-07-1991','dd-mm-yyyy'), NULL, 1, 'VP, Sales',
   31, 1400, NULL);
INSERT INTO emp VALUES (
   4, 'Quick-To-See', 'Mark', 'mquickto', 
   to_date('07-04-1990','dd-mm-yyyy'), NULL, 1, 'VP, Finance', 
   10, 1450, NULL);
INSERT INTO emp VALUES (
   5, 'Ropeburn', 'Audry', 'aropebur',
   to_date('04-MAR-1990','dd-mon-yyyy'), NULL, 1, 'VP, Administration',
   50, 1550, NULL);
INSERT INTO emp VALUES (
   6, 'Urguhart', 'Molly', 'murguhar',
   to_date('18-01-1991','dd-mm-yyyy'), NULL, 2, 'Warehouse Manager',
   41, 1200, NULL);
INSERT INTO emp VALUES (
   7, 'Menchu', 'Roberta', 'rmenchu',
   to_date('14-05-1990','dd-mm-yyyy'), NULL, 2, 'Warehouse Manager',
   42, 1250, NULL);
INSERT INTO emp VALUES (
   8, 'Biri', 'Ben', 'bbiri',
   to_date('07-04-1990','dd-mm-yyyy'), NULL, 2, 'Warehouse Manager',
   43, 1100, NULL);
INSERT INTO emp VALUES (
   9, 'Catchpole', 'Antoinette', 'acatchpo',
   to_date('09-02-1992','dd-mm-yyyy'), NULL, 2, 'Warehouse Manager',
   44, 1300, NULL);
INSERT INTO emp VALUES (
   10, 'Havel', 'Marta', 'mhavel',
   to_date('27-02-1991','dd-mm-yyyy'), NULL, 2, 'Warehouse Manager',
   45, 1307, NULL);
INSERT INTO emp VALUES (
   11, 'Magee', 'Colin', 'cmagee',
   to_date('14-05-1990','dd-mm-yyyy'), NULL, 3, 'Sales Representative',
   31, 1400, 10);
INSERT INTO emp VALUES (
   12, 'Giljum', 'Henry', 'hgiljum',
   to_date('18-01-1992','dd-mm-yyyy'), NULL, 3, 'Sales Representative',
   32, 1490, 12.5);
INSERT INTO emp VALUES (
   13, 'Sedeghi', 'Yasmin', 'ysedeghi',
   to_date('18-02-1991','dd-mm-yyyy'), NULL, 3, 'Sales Representative',
   33, 1515, 10);
INSERT INTO emp VALUES (
   14, 'Nguyen', 'Mai', 'mnguyen',
   to_date('22-01-1992','dd-mm-yyyy'), NULL, 3, 'Sales Representative',
   34, 1525, 15);
INSERT INTO emp VALUES (
   15, 'Dumas', 'Andre', 'adumas',
   to_date('09-10-1991','dd-mm-yyyy'), NULL, 3, 'Sales Representative',
   35, 1450, 17.5);
INSERT INTO emp VALUES (
   16, 'Maduro', 'Elena', 'emaduro',
   to_date('07-02-1992','dd-mm-yyyy'), NULL, 6, 'Stock Clerk',
   41, 1400, NULL);
INSERT INTO emp VALUES (
   17, 'Smith', 'George', 'gsmith',
   to_date('08-MAR-1990','dd-mon-yyyy'), NULL, 6, 'Stock Clerk',
   41, 940, NULL);
INSERT INTO emp VALUES (
   18, 'Nozaki', 'Akira', 'anozaki',
   to_date('09-02-1991','dd-mm-yyyy'), NULL, 7, 'Stock Clerk',
   42, 1200, NULL);
INSERT INTO emp VALUES (
   19, 'Patel', 'Vikram', 'vpatel',
   to_date('06-09-1991','dd-mm-yyyy'), NULL, 7, 'Stock Clerk',
   42, 795, NULL);
INSERT INTO emp VALUES (
   20, 'Newman', 'Chad', 'cnewman',
   to_date('21-08-1991','dd-mm-yyyy'), NULL, 8, 'Stock Clerk',
   43, 750, NULL);
INSERT INTO emp VALUES (
   21, 'Markarian', 'Alexander', 'amarkari',
   to_date('26-05-1991','dd-mm-yyyy'), NULL, 8, 'Stock Clerk',
   43, 850, NULL);
INSERT INTO emp VALUES (
   22, 'Chang', 'Eddie', 'echang',
   to_date('30-11-1990','dd-mm-yyyy'), NULL, 9, 'Stock Clerk',
   44, 800, NULL);
INSERT INTO emp VALUES (
   23, 'Patel', 'Radha', 'rpatel',
   to_date('17-10-1990','dd-mm-yyyy'), NULL, 9, 'Stock Clerk',
   34, 795, NULL);
INSERT INTO emp VALUES (
   24, 'Dancs', 'Bela', 'bdancs',
   to_date('17-MAR-1991','dd-mm-yyyy'), NULL, 10, 'Stock Clerk',
   45, 860, NULL);
INSERT INTO emp VALUES (
   25, 'Schwartz', 'Sylvie', 'sschwart',
   to_date('09-05-1991','dd-mm-yyyy'), NULL, 10, 'Stock Clerk',
   45, 1100, NULL);
COMMIT;

--13
INSERT INTO loans (
    loan_id,
    loan_date,
    payment_method,
    loan_expense
)
    SELECT
        id + 100,
        start_date,
        userid,
        salary
    FROM
        emp;
--14
SELECT * FROM loans;

