--1
SELECT LAST_NAME "NAZWISKO", FIRST_NAME "IMIĘ", DEPT_ID "ID", NAME "NAZWA DEPARTAMENTU"
FROM EMP, DEPT
WHERE EMP.DEPT_ID = DEPT.ID;
 
--2
SELECT DEPT.ID, DEPT.REGION_ID "NR REGIONU", REGION.NAME "NAZWA REGIONU"
FROM DEPT,REGION
WHERE DEPT.REGION_ID = REGION.ID;
      
--3
SELECT LAST_NAME "NAZWISKO", FIRST_NAME "IMIĘ", DEPT_ID "NR DEPARTAMENTU", NAME "NAZWA DEPARTAMENTU"
FROM EMP, DEPT
WHERE EMP.DEPT_ID = DEPT.ID AND EMP.LAST_NAME = 'Menchu';
   
--4
SELECT EMP.LAST_NAME "NAZWISKO", REGION.NAME "NAZWA REGIONU", EMP.COMMISSION_PCT "PROWIZJA"
FROM EMP, REGION, DEPT
WHERE EMP.COMMISSION_PCT IS NOT NULL AND EMP.DEPT_ID = DEPT.ID AND DEPT.REGION_ID = REGION.ID;
   
--5
SELECT NVL(EMP.LAST_NAME, '-') "NAZWISKO", NVL(TO_CHAR(EMP.ID), '-') "ID", CUSTOMER.NAME "NAZWA KLIENTA"
FROM EMP, CUSTOMER
WHERE EMP.ID(+) = CUSTOMER.SALES_REP_ID;
      
--6
SELECT E1.LAST_NAME || ' pracuje dla ' || E2.LAST_NAME "KTO DLA KOGO"
FROM EMP E1, EMP E2
WHERE E1.MANAGER_ID = E2.ID;
   
--7
SELECT CUSTOMER.NAME "NAZWA KLIENTA", EMP.LAST_NAME "NAZWISKO", TO_CHAR(ORD.DATE_ORDERED,'YY/MM/DD') "DATA ZAMÓWIENIA", ITEM.QUANTITY_SHIPPED "LICZBA", PRODUCT.NAME "NAZWA"
FROM CUSTOMER, EMP, ORD, ITEM, PRODUCT
WHERE ORD.SALES_REP_ID = EMP.ID AND ORD.ID = ITEM.ORD_ID AND ITEM.PRODUCT_ID = PRODUCT.ID AND CUSTOMER.ID = ORD.CUSTOMER_ID AND ORD.ID = 101;
     
--8
SELECT CUSTOMER.ID "NR KLIENTA", CUSTOMER.NAME "NAZWA KLIENTA", NVL(TO_CHAR(ORD.ID), '-') "NR ZAMÓWIENIA"
FROM CUSTOMER, ORD
WHERE CUSTOMER.ID = ORD.CUSTOMER_ID(+)
ORDER BY 1;
     
--9
SELECT MAX(SALARY) "MAKSYMALNA", MIN(SALARY) "MINIMALNA", SUM(SALARY)/COUNT(SALARY) "ŚREDNIA", SUM(SALARY) "SUMA", COUNT(SALARY) "LICZBA PRACOWNIKÓW"
FROM EMP;
 
--10
SELECT MIN(LAST_NAME) "PIERWSZE NAZWISKO", MAX(LAST_NAME) "OSTATNIE NAZWISKO"
FROM EMP; 
 
--11
SELECT COUNT(EMP.LAST_NAME) "LICZBA PRACOWNIKÓW"
FROM EMP
WHERE DEPT_ID = 31 AND COMMISSION_PCT IS NOT NULL;